import React, { useState } from 'react';
import {
  Sparkles,
  BookOpen,
  ArrowRight,
  AlertTriangle,
  Lightbulb,
  Cpu,
  HelpCircle,
  Layers,
  Send,
  Loader2,
  CheckCircle2,
  ChevronRight,
  Atom,
} from 'lucide-react';
import { MathRenderer } from './MathRenderer';
import { AI_PROFESSORS, Professor, getProfessorById } from '../data/professors';
import { FEATURED_EQUATIONS, EquationBreakdown, MoleculeRole } from '../data/sampleEquations';
import { formatCleanErrorMessage } from '../utils/errorUtils';
import { RajatHallmark } from './RajatHallmark';

interface EquationExplainerViewProps {
  onAskProfessor?: (professorId: string, initialPrompt: string) => void;
}

export const EquationExplainerView: React.FC<EquationExplainerViewProps> = ({
  onAskProfessor,
}) => {
  const [selectedEquation, setSelectedEquation] = useState<EquationBreakdown>(FEATURED_EQUATIONS[0]);
  const [customEquationInput, setCustomEquationInput] = useState('');
  const [selectedProfessorId, setSelectedProfessorId] = useState<Professor['id']>('kevin');
  const [isExplaining, setIsExplaining] = useState(false);
  const [aiExplanation, setAiExplanation] = useState<{
    equation: string;
    professorName: string;
    story: string;
    steps: string[];
    traps: string[];
    memoryHook: string;
    rawMarkdown?: string;
  } | null>(null);
  const [explainError, setExplainError] = useState<string | null>(null);

  const activeProfessor = getProfessorById(selectedProfessorId);

  const handleExplainCustom = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    const query = customEquationInput.trim();
    if (!query) return;

    setIsExplaining(true);
    setExplainError(null);

    try {
      const res = await fetch('/api/explain-equation', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          equation: query,
          professorId: selectedProfessorId,
        }),
      });

      const data = await res.json();
      if (data.error) throw new Error(data.error);

      setAiExplanation({
        equation: query,
        professorName: activeProfessor.name,
        story: data.plainEnglishStory || data.story || 'Breakdown generated by ' + activeProfessor.name,
        steps: data.stepByStep || data.steps || [],
        traps: data.examTraps || data.traps || [],
        memoryHook: data.memoryHook || '',
        rawMarkdown: data.rawMarkdown,
      });
    } catch (err: any) {
      console.error(err);
      setExplainError(formatCleanErrorMessage(err, 'Failed to explain equation. Please try again.'));
    } finally {
      setIsExplaining(false);
    }
  };

  const getMoleculeColorClasses = (color: MoleculeRole['color']) => {
    switch (color) {
      case 'emerald':
        return 'bg-emerald-50 border-emerald-200 text-emerald-950 ring-emerald-500/20';
      case 'amber':
        return 'bg-amber-50 border-amber-200 text-amber-950 ring-amber-500/20';
      case 'blue':
        return 'bg-blue-50 border-blue-200 text-blue-950 ring-blue-500/20';
      case 'purple':
        return 'bg-purple-50 border-purple-200 text-purple-950 ring-purple-500/20';
      case 'rose':
        return 'bg-rose-50 border-rose-200 text-rose-950 ring-rose-500/20';
      case 'slate':
      default:
        return 'bg-slate-50 border-slate-200 text-slate-900 ring-slate-500/20';
    }
  };

  const getBadgeColorClasses = (color: MoleculeRole['color']) => {
    switch (color) {
      case 'emerald':
        return 'bg-emerald-100 text-emerald-800 border-emerald-300';
      case 'amber':
        return 'bg-amber-100 text-amber-800 border-amber-300';
      case 'blue':
        return 'bg-blue-100 text-blue-800 border-blue-300';
      case 'purple':
        return 'bg-purple-100 text-purple-800 border-purple-300';
      case 'rose':
        return 'bg-rose-100 text-rose-800 border-rose-300';
      case 'slate':
      default:
        return 'bg-slate-200 text-slate-800 border-slate-300';
    }
  };

  return (
    <div className="max-w-6xl mx-auto space-y-6 pb-12">
      {/* Header Banner */}
      <div className="bg-gradient-to-r from-slate-900 via-slate-800 to-indigo-950 rounded-2xl p-6 sm:p-8 text-white shadow-lg relative overflow-hidden border border-slate-700/50">
        <div className="absolute -right-10 -bottom-10 w-64 h-64 bg-emerald-500/10 rounded-full blur-3xl pointer-events-none" />
        <div className="relative z-10 max-w-3xl space-y-3">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-500/20 border border-emerald-400/30 text-emerald-300 text-xs font-semibold tracking-wide">
            <Atom className="w-3.5 h-3.5 text-emerald-400 animate-pulse" />
            <span>Intuitive Visual Equation Explainer</span>
          </div>

          <h1 className="text-2xl sm:text-3xl font-bold tracking-tight text-white">
            Equations Don&apos;t Have to Look Like Jargon
          </h1>

          <p className="text-slate-300 text-sm sm:text-base leading-relaxed">
            Raw formulas like <span className="font-mono text-emerald-300 bg-slate-800/80 px-1.5 py-0.5 rounded text-xs">Pyruvate + CoA-SH + NAD⁺ ➔ Acetyl-CoA + CO₂ + NADH</span> often confuse students.
            We break down every reactant into its <strong>real-life job</strong>, track the carbon and energy transfers, and provide plain-English mental models guided by your <strong>4 Specialized AI Professors</strong>.
          </p>

          {/* Quick professor badges */}
          <div className="pt-2 flex flex-wrap items-center gap-2 text-xs">
            <span className="text-slate-400 font-medium">Explained by 4 AI Specialists:</span>
            {AI_PROFESSORS.map((prof) => (
              <button
                key={prof.id}
                onClick={() => setSelectedProfessorId(prof.id)}
                className={`px-2.5 py-1 rounded-lg border text-xs font-semibold flex items-center gap-1.5 transition ${
                  selectedProfessorId === prof.id
                    ? 'bg-white text-slate-900 border-white shadow-sm'
                    : 'bg-slate-800/80 text-slate-300 border-slate-700 hover:bg-slate-700'
                }`}
              >
                <span>{prof.avatarEmoji}</span>
                <span>{prof.name}</span>
                <span className="text-[10px] text-slate-400 font-normal">({prof.subject.split('&')[0].trim()})</span>
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Preset Selector tabs */}
      <div className="flex items-center justify-between gap-3 overflow-x-auto pb-1 border-b border-slate-200">
        <div className="flex items-center gap-2">
          {FEATURED_EQUATIONS.map((eq) => {
            const isSelected = selectedEquation.id === eq.id && !aiExplanation;
            return (
              <button
                key={eq.id}
                onClick={() => {
                  setSelectedEquation(eq);
                  setAiExplanation(null);
                  setSelectedProfessorId(eq.recommendedProfessorId);
                }}
                className={`px-4 py-2 rounded-xl text-xs font-bold transition whitespace-nowrap flex items-center gap-2 ${
                  isSelected
                    ? 'bg-emerald-700 text-white shadow-sm'
                    : 'bg-white text-slate-700 hover:bg-slate-100 border border-slate-200'
                }`}
              >
                <BookOpen className="w-3.5 h-3.5" />
                <span>{eq.title}</span>
              </button>
            );
          })}
        </div>

        <span className="text-xs text-slate-500 font-medium hidden sm:inline">
          Choose a featured exam reaction or analyze any equation below
        </span>
      </div>

      {/* MAIN EQUATION CARD */}
      {!aiExplanation && (
        <div className="space-y-6">
          {/* Formula Display Banner */}
          <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6 sm:p-8 space-y-6">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-100 pb-4">
              <div>
                <span className="text-[11px] font-bold uppercase tracking-wider text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded border border-emerald-200">
                  {selectedEquation.subject}
                </span>
                <h2 className="text-xl font-bold text-slate-900 mt-1">
                  {selectedEquation.title}
                </h2>
              </div>

              <div className="flex items-center gap-2">
                <span className="text-xs text-slate-500">Recommended Guide:</span>
                <div className="flex items-center gap-1.5 px-2.5 py-1 bg-slate-100 rounded-lg text-xs font-semibold text-slate-800">
                  <span>{activeProfessor.avatarEmoji}</span>
                  <span>{activeProfessor.name}</span>
                </div>
              </div>
            </div>

            {/* LaTeX Math Display */}
            <div className="bg-slate-950 rounded-xl p-5 text-white shadow-inner border border-slate-800 flex flex-col items-center justify-center min-h-[90px]">
              <div className="text-[10px] uppercase font-bold text-slate-400 tracking-wider mb-2">
                Formal Chemical / Mathematical Equation
              </div>
              <MathRenderer latex={selectedEquation.rawLatex} className="text-lg sm:text-xl text-emerald-300 font-medium" />
            </div>

            {/* Plain English Translation Callout */}
            <div className="p-4 sm:p-5 rounded-xl bg-gradient-to-r from-emerald-50 to-teal-50 border border-emerald-200 text-slate-800 space-y-2">
              <div className="flex items-center gap-2">
                <span className="p-1.5 bg-emerald-600 text-white rounded-lg shadow-xs">
                  <Lightbulb className="w-4 h-4" />
                </span>
                <span className="font-bold text-sm text-emerald-950">
                  How to Understand This in Plain English (No Jargon)
                </span>
              </div>
              <p className="text-slate-700 text-sm leading-relaxed pl-8 font-normal">
                {selectedEquation.plainEnglishStory}
              </p>
              <div className="pl-8 pt-1 text-xs text-emerald-800 font-medium flex items-center gap-2">
                <span>📍 <strong>Location:</strong> {selectedEquation.whereItHappens}</span>
                <span className="text-emerald-300">•</span>
                <span>⚙️ <strong>Catalyst:</strong> {selectedEquation.theTransformer.name}</span>
              </div>
            </div>

            {/* Visual Reactants -> Machine -> Products Flow */}
            <div className="space-y-4 pt-2">
              <div className="flex items-center justify-between">
                <h3 className="text-sm font-bold uppercase tracking-wider text-slate-500">
                  Visual Molecular Transformation Flow
                </h3>
                <span className="text-xs text-slate-400 font-medium">
                  {selectedEquation.reactants.length} Inputs ➔ {selectedEquation.products.length} Outputs
                </span>
              </div>

              <div className="grid grid-cols-1 lg:grid-cols-11 gap-4 items-stretch">
                {/* 1. What Goes In (Reactants) */}
                <div className="lg:col-span-5 space-y-2.5">
                  <div className="text-xs font-bold text-slate-700 flex items-center gap-1.5 pb-1 border-b border-slate-200">
                    <span className="w-2 h-2 rounded-full bg-blue-500" />
                    <span>WHAT GOES IN (Reactants)</span>
                  </div>

                  <div className="space-y-2">
                    {selectedEquation.reactants.map((mol, idx) => (
                      <div
                        key={idx}
                        className={`p-3.5 rounded-xl border transition shadow-xs ${getMoleculeColorClasses(mol.color)}`}
                      >
                        <div className="flex items-start justify-between gap-2">
                          <div>
                            <div className="font-bold text-sm text-slate-900 flex items-center gap-2">
                              <span>{mol.name}</span>
                              {mol.carbonCount && (
                                <span className="text-[10px] font-semibold px-1.5 py-0.5 rounded bg-white/80 border border-slate-300 text-slate-700">
                                  {mol.carbonCount}
                                </span>
                              )}
                            </div>
                            <div className="font-mono text-xs text-slate-600 mt-0.5">
                              {mol.formula}
                            </div>
                          </div>
                          <span className={`text-[10px] font-bold px-2 py-0.5 rounded border whitespace-nowrap ${getBadgeColorClasses(mol.color)}`}>
                            {mol.badge}
                          </span>
                        </div>
                        <p className="text-xs text-slate-600 mt-1.5 leading-relaxed">
                          {mol.plainEnglishRole}
                        </p>
                      </div>
                    ))}
                  </div>
                </div>

                {/* 2. The Middle Transformer Arrow */}
                <div className="lg:col-span-1 flex flex-col items-center justify-center py-4 lg:py-0">
                  <div className="w-10 h-10 rounded-full bg-emerald-600 text-white flex items-center justify-center shadow-md">
                    <ArrowRight className="w-5 h-5 hidden lg:block" />
                    <span className="text-xs font-bold lg:hidden">▼</span>
                  </div>
                  <span className="text-[10px] font-bold text-slate-500 uppercase tracking-widest mt-2 text-center">
                    Reaction Engine
                  </span>
                </div>

                {/* 3. What Comes Out (Products) */}
                <div className="lg:col-span-5 space-y-2.5">
                  <div className="text-xs font-bold text-slate-700 flex items-center gap-1.5 pb-1 border-b border-slate-200">
                    <span className="w-2 h-2 rounded-full bg-emerald-500" />
                    <span>WHAT COMES OUT (Products)</span>
                  </div>

                  <div className="space-y-2">
                    {selectedEquation.products.map((mol, idx) => (
                      <div
                        key={idx}
                        className={`p-3.5 rounded-xl border transition shadow-xs ${getMoleculeColorClasses(mol.color)}`}
                      >
                        <div className="flex items-start justify-between gap-2">
                          <div>
                            <div className="font-bold text-sm text-slate-900 flex items-center gap-2">
                              <span>{mol.name}</span>
                              {mol.carbonCount && (
                                <span className="text-[10px] font-semibold px-1.5 py-0.5 rounded bg-white/80 border border-slate-300 text-slate-700">
                                  {mol.carbonCount}
                                </span>
                              )}
                            </div>
                            <div className="font-mono text-xs text-slate-600 mt-0.5">
                              {mol.formula}
                            </div>
                          </div>
                          <span className={`text-[10px] font-bold px-2 py-0.5 rounded border whitespace-nowrap ${getBadgeColorClasses(mol.color)}`}>
                            {mol.badge}
                          </span>
                        </div>
                        <p className="text-xs text-slate-600 mt-1.5 leading-relaxed">
                          {mol.plainEnglishRole}
                        </p>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>

            {/* The 3 Steps Broken Down */}
            <div className="pt-4 border-t border-slate-100 space-y-3">
              <h3 className="text-sm font-bold text-slate-900 flex items-center gap-2">
                <Layers className="w-4 h-4 text-emerald-600" />
                <span>The 3 Coordinated Mechanism Steps</span>
              </h3>

              <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                {selectedEquation.theThreeKeySteps.map((step, idx) => (
                  <div key={idx} className="p-4 rounded-xl bg-slate-50 border border-slate-200 space-y-1.5">
                    <div className="flex items-center gap-2 text-sm font-bold text-slate-900">
                      <span>{step.icon}</span>
                      <span>{step.title}</span>
                    </div>
                    <p className="text-xs text-slate-600 leading-relaxed">
                      {step.description}
                    </p>
                  </div>
                ))}
              </div>
            </div>

            {/* Exam Traps & Memory Hook */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2">
              <div className="p-4 rounded-xl bg-amber-50 border border-amber-200 space-y-2">
                <div className="flex items-center gap-2 text-xs font-bold text-amber-900 uppercase tracking-wide">
                  <AlertTriangle className="w-4 h-4 text-amber-600" />
                  <span>High-Frequency Exam Traps</span>
                </div>
                <div className="space-y-1.5 text-xs text-slate-700">
                  {selectedEquation.examTraps.map((trap, idx) => (
                    <p key={idx} className="leading-relaxed">
                      {trap}
                    </p>
                  ))}
                </div>
              </div>

              <div className="p-4 rounded-xl bg-indigo-50 border border-indigo-200 flex flex-col justify-between space-y-3">
                <div className="space-y-1.5">
                  <div className="flex items-center gap-2 text-xs font-bold text-indigo-900 uppercase tracking-wide">
                    <Lightbulb className="w-4 h-4 text-indigo-600" />
                    <span>Memory Mnemonic / Hook</span>
                  </div>
                  <p className="text-xs text-indigo-950 font-semibold leading-relaxed">
                    {selectedEquation.memoryHook}
                  </p>
                </div>

                <button
                  onClick={() => {
                    if (onAskProfessor) {
                      onAskProfessor(
                        selectedEquation.recommendedProfessorId,
                        `Can you quiz me on ${selectedEquation.title} and the reaction: ${selectedEquation.rawLatex}?`
                      );
                    }
                  }}
                  className="w-full py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg text-xs font-bold transition flex items-center justify-center gap-1.5 shadow-xs"
                >
                  <Sparkles className="w-3.5 h-3.5" />
                  <span>Ask {activeProfessor.name} to Quiz Me on This</span>
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* AI Custom Explanation Result */}
      {aiExplanation && (
        <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6 sm:p-8 space-y-6">
          <div className="flex items-center justify-between border-b border-slate-100 pb-4">
            <div>
              <span className="text-xs font-bold uppercase tracking-wide text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded border border-emerald-200">
                AI Professor Breakdown
              </span>
              <h2 className="text-xl font-bold text-slate-900 mt-1">
                Analysis by {aiExplanation.professorName}
              </h2>
            </div>
            <button
              onClick={() => setAiExplanation(null)}
              className="text-xs font-semibold text-slate-500 hover:text-slate-800 bg-slate-100 px-3 py-1.5 rounded-lg transition"
            >
              Back to Featured Equations
            </button>
          </div>

          <div className="bg-slate-950 rounded-xl p-4 text-white">
            <div className="text-xs text-slate-400 font-mono mb-1">Target Equation:</div>
            <MathRenderer latex={aiExplanation.equation} className="text-lg text-emerald-300" />
          </div>

          <div className="p-4 rounded-xl bg-emerald-50 border border-emerald-200 text-slate-800 space-y-2">
            <h3 className="font-bold text-emerald-950 text-sm flex items-center gap-2">
              <Lightbulb className="w-4 h-4 text-emerald-600" />
              <span>Plain English Translation</span>
            </h3>
            <p className="text-slate-700 text-sm leading-relaxed">
              {aiExplanation.story}
            </p>
          </div>

          {aiExplanation.steps.length > 0 && (
            <div className="space-y-2">
              <h3 className="text-sm font-bold text-slate-900">Step-by-Step Breakdown:</h3>
              <div className="space-y-1.5">
                {aiExplanation.steps.map((st, i) => (
                  <div key={i} className="flex items-start gap-2 p-3 bg-slate-50 rounded-xl border border-slate-200 text-xs text-slate-700">
                    <span className="w-5 h-5 rounded-full bg-emerald-600 text-white font-bold flex items-center justify-center shrink-0 text-[10px]">
                      {i + 1}
                    </span>
                    <span className="leading-relaxed">{st}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {aiExplanation.traps.length > 0 && (
            <div className="p-4 rounded-xl bg-amber-50 border border-amber-200 space-y-1.5">
              <h3 className="text-xs font-bold uppercase tracking-wider text-amber-900 flex items-center gap-1.5">
                <AlertTriangle className="w-3.5 h-3.5 text-amber-600" />
                <span>Exam Traps to Watch Out For</span>
              </h3>
              {aiExplanation.traps.map((tr, i) => (
                <p key={i} className="text-xs text-slate-700 leading-relaxed">
                  • {tr}
                </p>
              ))}
            </div>
          )}

          {aiExplanation.memoryHook && (
            <div className="p-3 bg-indigo-50 border border-indigo-200 rounded-xl text-xs text-indigo-950 font-semibold flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-indigo-600 shrink-0" />
              <span>{aiExplanation.memoryHook}</span>
            </div>
          )}
        </div>
      )}

      {/* CUSTOM EQUATION SOLVER INPUT */}
      <div className="bg-white rounded-2xl border border-slate-200 shadow-sm p-6 space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
          <div>
            <h3 className="text-base font-bold text-slate-900 flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-emerald-600" />
              <span>Ask Any of the 4 AI Professors to Translate an Equation</span>
            </h3>
            <p className="text-xs text-slate-500 mt-0.5">
              Paste or type any reaction, formula, or math/physics equation (LaTeX or plain text).
            </p>
          </div>

          {/* Professor selector buttons */}
          <div className="flex items-center gap-1.5 p-1 bg-slate-100 rounded-xl">
            {AI_PROFESSORS.map((prof) => {
              const active = selectedProfessorId === prof.id;
              return (
                <button
                  key={prof.id}
                  onClick={() => setSelectedProfessorId(prof.id)}
                  className={`px-2.5 py-1 rounded-lg text-xs font-bold transition flex items-center gap-1 ${
                    active
                      ? `${prof.theme.accent} shadow-xs`
                      : 'text-slate-600 hover:text-slate-900'
                  }`}
                  title={`${prof.name} - ${prof.subject}`}
                >
                  <span>{prof.avatarEmoji}</span>
                  <span className="hidden md:inline">{prof.name}</span>
                </button>
              );
            })}
          </div>
        </div>

        <form onSubmit={handleExplainCustom} className="space-y-3">
          <div className="relative">
            <input
              type="text"
              value={customEquationInput}
              onChange={(e) => setCustomEquationInput(e.target.value)}
              placeholder="e.g. Pyruvate + CoA + NAD+ -> Acetyl-CoA + CO2 + NADH or 2H2 + O2 -> 2H2O or E = mc^2"
              className="w-full px-4 py-3 bg-slate-50 border border-slate-300 rounded-xl text-sm focus:outline-hidden focus:ring-2 focus:ring-emerald-500 focus:bg-white transition"
            />
          </div>

          <div className="flex flex-wrap items-center justify-between gap-3 pt-1">
            <div className="flex flex-wrap items-center gap-1.5 text-xs text-slate-500">
              <span className="font-semibold text-slate-700">Quick Try:</span>
              <button
                type="button"
                onClick={() => setCustomEquationInput('Pyruvate + CoA-SH + NAD+ -> Acetyl-CoA + CO2 + NADH')}
                className="px-2 py-0.5 rounded bg-slate-100 hover:bg-slate-200 text-slate-700 transition"
              >
                Pyruvate Link
              </button>
              <button
                type="button"
                onClick={() => setCustomEquationInput('6CO2 + 6H2O -> C6H12O6 + 6O2')}
                className="px-2 py-0.5 rounded bg-slate-100 hover:bg-slate-200 text-slate-700 transition"
              >
                Photosynthesis
              </button>
              <button
                type="button"
                onClick={() => setCustomEquationInput('x = (-b ± sqrt(b^2 - 4ac)) / (2a)')}
                className="px-2 py-0.5 rounded bg-slate-100 hover:bg-slate-200 text-slate-700 transition"
              >
                Quadratic Formula
              </button>
              <button
                type="button"
                onClick={() => setCustomEquationInput('F = dp/dt = m*a')}
                className="px-2 py-0.5 rounded bg-slate-100 hover:bg-slate-200 text-slate-700 transition"
              >
                Newton Second Law
              </button>
            </div>

            <button
              type="submit"
              disabled={isExplaining || !customEquationInput.trim()}
              className="px-5 py-2.5 bg-emerald-600 hover:bg-emerald-700 disabled:opacity-50 text-white rounded-xl text-xs font-bold shadow-md transition flex items-center gap-2"
            >
              {isExplaining ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  <span>{activeProfessor.name} is Translating...</span>
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4" />
                  <span>Translate with {activeProfessor.name}</span>
                </>
              )}
            </button>
          </div>

          {explainError && (
            <div className="p-3 bg-rose-50 border border-rose-200 text-rose-800 text-xs rounded-xl flex items-center gap-2">
              <AlertTriangle className="w-4 h-4 shrink-0 text-rose-600" />
              <span>{explainError}</span>
            </div>
          )}
        </form>
      </div>

      <RajatHallmark />
    </div>
  );
};
